### ISSUE TITLE
import config --> unexpected identifier

### ISSUE THREAD

**Issue by franciscouhlenbrok** [jscomplete/learn-fullstack-javascript#10]
import config from './config';
       ^^^^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at loader (/home/francisco/Documents/Programming Courses/learn-fullstack-javascript/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/francisco/Documents/Programming Courses/learn-fullstack-javascript/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at Object.<anonymous> (/home/francisco/Documents/Programming Courses/learn-fullstack-javascript/node_modules/babel-cli/lib/_babel-node.js:154:22)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)

That's the error message I get. I've cloned the current version with Tag 2.3-end from your GitHub. Can you help me?

**Comment by foad-heidari** [comment]
i don't know what repository do you mean. upload the files so i can help you.
the error here is bcz of the `import config from './config';`

**Comment by franciscouhlenbrok** [comment]
[learn-fullstack-javascript.zip](https://github.com/jscomplete/learn-fullstack-javascript/files/5816530/learn-fullstack-javascript.zip)

That's my repository

**Comment by foad-heidari** [comment]
i'm not gonna download that.
you can send the file here one by one

is this the repo which does have the error ? https://github.com/jscomplete/learn-fullstack-javascript/blob/final-code/server.js

**Comment by franciscouhlenbrok** [comment]
![Screenshot from 2021-01-14 20-39-38](https://user-images.githubusercontent.com/48553005/104640396-b8366880-56a8-11eb-943f-0fdcdf3448ab.png)

Yes it's that repo, but the version your find under the tag "2.3-end"

**Comment by foad-heidari** [comment]
this is not my repo any way
why you thing this is my repo?

i cant help you if you dont give enough information about your error and the files which related to your error

**Comment by franciscouhlenbrok** [comment]
Of course it's not your repo, as I opened this issue on @samerbuna's repo.
How do you assume that I'd  think that's your repo?

**Comment by SzDaniel95** [comment]
Maybe you use old version of NodeJS

**Comment by talanaji** [comment]
you can write it like this 
import config from './config.js';
