### ISSUE TITLE
Server render error

### ISSUE THREAD

**Issue by vikoultsev** [jscomplete/learn-fullstack-javascript#3]
Hi Samer.
When I start with files from `Exercise Files\Ch05\05_02` and enter the command `curl http://localhost:8080` I get this in my console:
```
{ Error: connect EADDRNOTAVAIL 0.0.0.0:8080
    at Object.exports._errnoException (util.js:1050:11)
    at exports._exceptionWithHostPort (util.js:1073:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)
  code: 'EADDRNOTAVAIL',
  errno: 'EADDRNOTAVAIL',
  syscall: 'connect',
  address: '0.0.0.0',
  port: 8080,
  config:
   { adapter: [Function: httpAdapter],
     transformRequest: { '0': [Function: transformRequest] },
     transformResponse: { '0': [Function: transformResponse] },
     timeout: 0,
     xsrfCookieName: 'XSRF-TOKEN',
     xsrfHeaderName: 'X-XSRF-TOKEN',
     maxContentLength: -1,
     validateStatus: [Function: validateStatus],
     headers:
      { Accept: 'application/json, text/plain, */*',
        'User-Agent': 'axios/0.15.3' },
     method: 'get',
     url: 'http://0.0.0.0:8080/api/contests',
     data: undefined },
  response: undefined }
```
and empty HTML markup:
```
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Naming Contests</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <link rel="stylesheet" href="/style.css" media="screen">
</head>
<body class="container">
  <div id="root"></div>
<script src="/bundle.js" charset="utf-8"></script>

</body>
</html>
```
All npm modules are installed.
Node.js ver. 7.9.0
npm ver. 4.2.0

**Comment by dargains** [comment]
what did you do to fix it?
