### ISSUE TITLE
Babel-node throwing error

### ISSUE THREAD

**Issue by nigellima** [jscomplete/learn-fullstack-javascript#7]
Following the steps at https://www.youtube.com/watch?v=kSsJKyTNOyw&index=5&list=PLndrmkbqEI8WrbdSUmxu0mxOB8ohahLrZ, I'm getting stuck at the ./node-modules/.bin/babel-node server.js

I'm getting this message:

Error: Cannot find module '../lib/babel-node'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:470:25)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/nigeldasilvalima/Dropbox/JsStack/fulljs/node_modules/.bin/babel-node:3:1)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)

I followed all the steps on this video and previous ones. I have no idea of why this is happening. I appreciate any helpt

**Comment by samerbuna** [comment]
All the files and tags of this repo were updated for things to work with the latest changes in the tools.
